GET https://cursoeverisprofe.azure-api.net/censo;rev=1/api/Census
Accept: text/xml

###

GET https://cursoeverisprofe2.azure-api.net/numeros/palabras?num=43210
Ocp-Apim-Subscription-Key: 88a4bd1164c24c8aa5f6aa12aedccded
Ocp-Apim-Trace: true